/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.cequals.greatdictator;

import net.cequals.greatdictator.service.DummySpeechRecognizer;
import net.cequals.greatdictator.speechcore.SpeechCore;
import net.cequals.greatdictator.speechcore.model.SpeechModel;
import net.cequals.greatdictator.speechcore.model.dto.SpeechData;
import net.cequals.greatdictator.speechcore.service.http.CSpeechClient;
import net.cequals.greatdictator.speechcore.service.http.KtorSpeechClient;
import net.cequals.lib.nullsafe.Op;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    static class A implements CSpeechClient.SpeechDataRetriever {

        @Override
        public Op<String> retrieve(String string, String string1) {
            return Op.valueOp("a");
        }

    }

    public static void main(String[] args) {
        var speechCore = new SpeechCore(new SpeechModel(new DummySpeechRecognizer(), new KtorSpeechClient()));
        speechCore.startDictation();
        var c = new CSpeechClient(new A());
        var testString = """
            {
                "sentences": [
                    {
                    "index": 0,
                    "parse": "(ROOT\n  (SBARQ\n    (WHNP (WP What))\n    (SQ (VBZ does)\n      (NP (PRP it))\n      (VP (VB look)\n        (PP (IN like)\n          (ADVP (RB now)))))))",
                    "sentiment": "Neutral"
                    }
                ]
            }
        """;
        try {
            SpeechData d = c.getMoshi().fromJson(testString);
            System.out.println(d.getSentences().get(0).getParse());
            Thread.sleep(7000);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
